### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by ATMLGG** [zepen/predict_Lottery_ticket#11]
手动创建了data文件夹拉取历史数据,运行train_model的时候报这个错:

ValueError: A target array with shape (2616, 24) was passed for an output of shape (None, 0) while using as loss `categorical_crossentropy`. This loss expects targets to have the same shape as the output.

**Comment by bx24** [comment]
我运行成功 没有值 不知道怎么回事 谢谢！
[INFO] 模型加载成功！
 * Serving Flask app "predict_api" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
运行完这结果 怎么办  呜呜

**Comment by zepen** [comment]
> output
构造损失函数出错，目标输出和喂给模型的不一致，检查下数据是不是有问题

**Comment by yexingyu9080** [comment]
1.需要手动创建data文件夹

**Comment by yexingyu9080** [comment]
1.需要手动创建data文件夹
2.tensorflow版本和cpu版本以及python版本对应
3.建模运行速度特别慢，我8核只能使用百分之十二，两天了还没完呢；笔记本六天了没有结束，不知道是不是我设置问题

**Comment by anshare2011** [comment]
运行结果就是给一个网页连接，提示Welcome to use，然后呢？折腾了半天就为说句helloworld吗？预测结果怎么出不来

**Comment by anshare2011** [comment]
运行速度挺快的，几分钟就出结果了，但是结果就是个这个
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [06/Jan/2021 22:37:57] "GET / HTTP/1.1" 200 -
点击地址后是Welcome to use!
不知道干了啥啊？折腾镇么半天图什么啊？

**Comment by anshare2011** [comment]
测试运行get_predict_result()函数也一直报错，是作者留了坑吗？

**Comment by zepen** [comment]
服务启动，访问预测结果是这个 url， http://127.0.0.1:5000/predict_api。
 get_predict_result 应该是不能直接测试的，看来大家对服务端知识有欠缺，我重写下readme好了
