### ISSUE TITLE
运行完成没有数据

### ISSUE THREAD

**Issue by bx24** [zepen/predict_Lottery_ticket#12]
我运行成功 没有值 不知道怎么回事 谢谢！
[INFO] 模型加载成功！

Serving Flask app "predict_api" (lazy loading)
Environment: production
WARNING: This is a development server. Do not use it in a production deployment.
Use a production WSGI server instead.
Debug mode: off
Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
运行完这结果 怎么办 呜呜

**Comment by zepen** [comment]
打开浏览器，输出 http://127.0.0.1:5000/predict_api/，应该能看到结果
