### ISSUE TITLE
调用@app.route('/predict_api', methods=['GET'])方法报错

### ISSUE THREAD

**Issue by FuXiangGit** [zepen/predict_Lottery_ticket#14]
File "F:/predict_Lottery_ticket-master/predict_api.py", line 40, in get_predict_result
    p_data = np.array(data_list).reshape([-1, 3, 1]).astype(np.float32)
ValueError: cannot reshape array of size 1 into shape (3,1)

**Comment by zepen** [comment]
最近开奖出现跳期，期号不连续，导致获取序列维度出错，我统一修复下这个问题
