### ISSUE TITLE
有参数的相关解释文档吗，谢谢了

### ISSUE THREAD

**Issue by ylpmikasa** [zepen/predict_Lottery_ticket#31]
# 模型相关参数
windows_size = 3
batch_size = 1
sequence_len = 6
red_n_class = 33
red_epochs = 1
red_embedding_size = 32
red_hidden_size = 32
red_layer_size = 1
blue_n_class = 16
blue_epochs = 1
blue_embedding_size = 32
blue_hidden_size = 32
blue_layer_size = 1

# 模型训练参数
red_learning_rate = 0.001
red_beta1 = 0.9
red_beta2 = 0.999
red_epsilon = 1e-08
blue_learning_rate = 0.001
blue_beta1 = 0.9
blue_beta2 = 0.999
blue_epsilon = 1e-08

**Comment by fei15115** [comment]
您好，我已经收到您的邮件，我会尽快查看回复，谢谢！
