### ISSUE TITLE
m1 chip not support ?

### ISSUE THREAD

**Issue by zhouxiongh** [zepen/predict_Lottery_ticket#33]
System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacBook Air Apple M1 chip, macOS Monterey version 12.2
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
TensorFlow installed from (source or binary): binary
TensorFlow version: 2.1.0
Python version: 3.6.12
Installed using virtualenv? pip? conda?: pip3

Describe the problem
when i run 
```
python train_model.py
[1]    59236 illegal hardware instruction  python train_model.py
```

**Comment by zepen** [comment]
May be tensorflow version is not mattch，try use other version？Or create conda env and pip install -r requirements.txt
