### ISSUE TITLE
每期都需要运行get_train_data.py和modeling.py吗

### ISSUE THREAD

**Issue by Las6040a** [zepen/predict_Lottery_ticket#34]
谢谢大神分享代码，已经能正常运行，请教：是否每期都需要运行get_train_data.py?
![Uploading 微信截图_20220331092811.png…]()

**Comment by Las6040a** [comment]
谢谢老大！！我是python刚入门小白，对于神经网络的技术无比向往，只是水平太低，只能对您膜拜！！！目前我都是采用统计的方法，利用区间比和值等等参数来判断，感觉很不靠谱，希望今后您能多多指教！！！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月31日(周四) 上午9:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zepen/predict_Lottery_ticket] 每期都需要运行get_train_data.py和modeling.py吗 (Issue #34)




 
Closed #34.

**Comment by zepen** [comment]
> 谢谢老大！！我是python刚入门小白，对于神经网络的技术无比向往，只是水平太低，只能对您膜拜！！！目前我都是采用统计的方法，利用区间比和值等等参数来判断，感觉很不靠谱，希望今后您能多多指教！！！
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年3月31日(周四) 上午9:39 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [zepen/predict_Lottery_ticket] 每期都需要运行get_train_data.py和modeling.py吗 (Issue #34) Closed #34. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

还是系统的学习下，机器学习相关吧，神经网络只是一种方法而已。事实上，它的问题很多。

**Comment by Las6040a** [comment]
> 

谢谢大神！！
