### ISSUE TITLE
500网站访问不了

### ISSUE THREAD

**Issue by wayfeel** [zepen/predict_Lottery_ticket#36]
能换网站吗

**Comment by zepen** [comment]
是的，最近发现了，网页居然不能访问了。需要找个稳定的网站了。

**Comment by wayfeel** [comment]
或者能不能加多个离线模式，如果网站访问不了，那就手动更新data文件，AI训练和结果预测就基于data数据，而不是再访问网站

**Comment by zepen** [comment]
> 或者能不能加多个离线模式，如果网站访问不了，那就手动更新data文件，AI训练和结果预测就基于data数据，而不是再访问网站

可以，应该多提供几个网站数据接口，保住一个挂了，其他还能用。这一个网站挂了，就没数据了，尴尬了。

**Comment by wayfeel** [comment]
哈哈哈，500能访问了，但数据图表还是打不开，我猜应该是站主被请喝咖啡了

**Comment by zepen** [comment]
> 哈哈哈，500能访问了，但数据图表还是打不开，我猜应该是站主被请喝咖啡了

是可以了，你还一直关注着，不错，不错
