### ISSUE TITLE
调用api，需要每次都运行模型吗？

### ISSUE THREAD

**Issue by pengyanbing84** [zepen/predict_Lottery_ticket#46]
因为每期都有开奖，如果调用api来获取预测结果，是不是先要跑训练模型，每次都要先抓最新的数据下来

**Comment by MyBirdVery6** [comment]
> 不用，模型训练好了，就可以对未来进行预测。api直接每天预测就行。

每天的预测结果好像是一样的？

**Comment by zepen** [comment]
> > 不用，模型训练好了，就可以对未来进行预测。api直接每天预测就行。
> 
> 每天的预测结果好像是一样的？

一段时间内，好像不会有太大变化
