### ISSUE TITLE
可以改为使用GPU进行训练么

### ISSUE THREAD

**Issue by jiangfubang** [zepen/predict_Lottery_ticket#55]
如题

**Comment by A-biao96** [comment]
可以，加一行代码。
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0" 

不过会有警告，起不到加速作用，并没有用cpu运行的快，原因和代码编写有关，目前还没解决。

**Comment by zepen** [comment]
这点数据量和模型参数，GPU犹如杀鸡用牛刀
