### ISSUE TITLE
小白问个问题 can not import name dtensor

### ISSUE THREAD

**Issue by goodman777** [zepen/predict_Lottery_ticket#57]
在安装完依赖后，运行train model 报错

**Comment by thxwork** [comment]
我也是

**Comment by pythonlw** [comment]
版本问题，可以参考一下版本
Flask==2.0.3
Jinja2==3.1.1
tensorflow-cpu==2.6.1
tensorflow-addons==0.14.0
requests==2.22.0
keras==2.6.0
beautifulsoup4==4.9.3
pandas==1.0.0
numpy==1.19.5
lxml==4.6.2
gunicorn==20.1.0
gevent==1.4.0
loguru==0.6.0
grpcio==1.46.0
protobuf==3.18.1

**Comment by lujiaweicy** [comment]
报错是因为[keras]版本太高，需要降低到和tensorflow版本一致， pip install keras==2.6.0

**Comment by zepen** [comment]
> 报错是因为[keras]版本太高，需要降低到和tensorflow版本一致， pip install keras==2.6.0

正解

**Comment by fei15115** [comment]
您好，我已经收到您的邮件，我会尽快查看回复，谢谢！
