### ISSUE TITLE
load model报错

### ISSUE THREAD

**Issue by KittenCN** [zepen/predict_Lottery_ticket#59]
我尝试在train里面增加load model的代码，以期能中断后重新开始train。
代码类似run_api中的load model。
但是在sess.run（）后会报错：
Fetch argument <tf.Operation 'Adam' type=NoOp> cannot be interpreted as a Tensor. 

Tensorflow写的不多，求解惑

**Comment by fei15115** [comment]
您好，我已经收到您的邮件，我会尽快查看回复，谢谢！

**Comment by zepen** [comment]
调整下tensorflow版本试试，最好按照requirements.txt文件中的库进行安装
