### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by smilencecc** [zepen/predict_Lottery_ticket#61]
大佬能写个详细点的教程
报错报的我脑瓜子嗡嗡的。。。
![1](https://user-images.githubusercontent.com/77428601/192660158-d1b3654b-e9f3-46bb-8433-0611530917e4.png)

**Comment by A-biao96** [comment]
你运行的地方搞错了，用anaconda powershell prompt 终端界面  cd到文件位置运行，或者在pycharm里运行

**Comment by A-biao96** [comment]
还有看看包的版本对不对

**Comment by smilencecc** [comment]
> 还有看看包的版本对不对

我用的是python310的版本

**Comment by smilencecc** [comment]
> 你运行的地方搞错了，用anaconda powershell prompt 终端界面 cd到文件位置运行，或者在pycharm里运行

这个事要再安装软件么  我是菜狗

**Comment by A-biao96** [comment]
> > 你运行的地方搞错了，用anaconda powershell prompt 终端界面 cd到文件位置运行，或者在pycharm里运行
> 
> 这个事要再安装软件么 我是菜狗

首先，这个要安装tensorflow，然后可以使用anaconda安装tensorflow，使用pycharm和anaconda powershell prompt 都可运行

**Comment by smilencecc** [comment]
> > > 你运行的地方搞错了，用anaconda powershell prompt 终端界面 cd到文件位置运行，或者在pycharm里运行
> > 
> > 
> > 这个事要再安装软件么 我是菜狗
> 
> 首先，这个要安装tensorflow，然后可以使用anaconda安装tensorflow，使用pycharm和anaconda powershell prompt 都可运行

对版本有没有要求  我试试

**Comment by smilencecc** [comment]
> > > 你运行的地方搞错了，用anaconda powershell prompt 终端界面 cd到文件位置运行，或者在pycharm里运行
> > 
> > 
> > 这个事要再安装软件么 我是菜狗
> 
> 首先，这个要安装tensorflow，然后可以使用anaconda安装tensorflow，使用pycharm和anaconda powershell prompt 都可运行

软件和环境都已经安装   但是运行之后还是有点小问题
![223](https://user-images.githubusercontent.com/77428601/196021708-b5d8ee7e-46c7-487e-a180-16c0a025415e.png)
![2746](https://user-images.githubusercontent.com/77428601/196021712-0b52a049-c3e6-4034-9762-ecff0b5facb1.png)

**Comment by zepen** [comment]
> > > > 你运行的地方搞错了，用anaconda powershell prompt 终端界面 cd到文件位置运行，或者在pycharm里运行
> > > 
> > > 
> > > 这个事要再安装软件么 我是菜狗
> > 
> > 
> > 首先，这个要安装tensorflow，然后可以使用anaconda安装tensorflow，使用pycharm和anaconda powershell prompt 都可运行
> 
> 软件和环境都已经安装 但是运行之后还是有点小问题 ![223](https://user-images.githubusercontent.com/77428601/196021708-b5d8ee7e-46c7-487e-a180-16c0a025415e.png) ![2746](https://user-images.githubusercontent.com/77428601/196021712-0b52a049-c3e6-4034-9762-ecff0b5facb1.png)

看下这个目录下，是不是确实有requirements.txt这个文件，程序提示就是找不到这个文件。
