### ISSUE TITLE
摸索了二个小时，试试行不行

### ISSUE THREAD

**Issue by lujiaweicy** [zepen/predict_Lottery_ticket#62]
{"red_1": 1, "red_2": 3, "red_3": 7, "red_4": 10, "red_5": 32, "red_6": 33, "blue": 12}

**Comment by A-biao96** [comment]
不太准，买一注，可以玩玩
这个前端界面容易崩，我把它改了，直接打印输。   
lucky_number = get_predict_result()
print("预测号码为：" + str (lucky_number))
还有代码里训练时，每次减 1 训练，输出加 1，这样训练也要考虑下，我也把它改掉了

**Comment by zepen** [comment]
> 不太准，买一注，可以玩玩 这个前端界面容易崩，我把它改了，直接打印输。 lucky_number = get_predict_result() print("预测号码为：" + str (lucky_number)) 还有代码里训练时，每次减 1 训练，预测run_api.py 输出加 1，这样训练也要考虑下，我也把它改掉了

优秀！
