### ISSUE TITLE
依赖版本问题

### ISSUE THREAD

**Issue by KittenCN** [zepen/predict_Lottery_ticket#65]
经过测试，0.10.0版本的tensorflow-addons并不支持2.6.1版本的tensorflow-cpu，并且，2.5以上版本的tensorflow-cpu貌似不支持CRF，2.4版本的tensorflow-cpu不能很好的进行序列化，因此，个人推荐以下依赖版本：
tensorflow-cpu==2.3.*
tensorflow-addons==0.13.*
requests
keras
beautifulsoup4
pandas
numpy
lxml
loguru
grpcio
protobuf

但是，这样还是会有save时序列化warning的小问题，测试后发觉不影响使用

**Comment by chuzihanglyc** [comment]
> 经过测试，0.10.0版本的tensorflow-addons并不支持2.6.1版本的tensorflow-cpu，并且，2.5以上版本的tensorflow-cpu貌似不支持CRF，2.4版本的tensorflow-cpu不能很好的进行序列化，因此，个人推荐以下依赖版本： tensorflow-cpu==2.3.* tensorflow-addons==0.13.* requests keras beautifulsoup4 pandas numpy lxml loguru grpcio protobuf
> 
> 但是，这样还是会有save时序列化warning的小问题，测试后发觉不影响使用

*是多少啊，可以取0吗，1吗
