### ISSUE TITLE
想改进模型，有几个参数帮忙理解一下

### ISSUE THREAD

**Issue by StevenGao6** [zepen/predict_Lottery_ticket#77]
"windows_size": 3,
            "batch_size": 1,
            "sequence_len": 6,
            "red_n_class": 33,
            "red_epochs": 1,
            "red_embedding_size": 32,
            "red_hidden_size": 32,
            "red_layer_size": 1,
            "blue_n_class": 16,
            "blue_epochs": 1,
            "blue_embedding_size": 32,
            "blue_hidden_size": 32,
            "blue_layer_size": 1

**Comment by zepen** [comment]
可以加群，参考群文件

**Comment by chuzihanglyc** [comment]
> 

群是多少
