### ISSUE TITLE
蓝球怎么不是1就是12？

### ISSUE THREAD

**Issue by krasus1995** [zepen/predict_Lottery_ticket#78]

**Comment by triangle959** [comment]
![image](https://github.com/zepen/predict_Lottery_ticket/assets/34617914/86becb98-7312-4250-807b-45bbee2ad845)
这个训练代码的分数据集感觉有问题，模型测试环节竟然能100%命中测试集

**Comment by zepen** [comment]
蓝球因为是单球，随机性很大

**Comment by kkltmoyu** [comment]
我也遇到这个问题，为什么预测结果蓝色不是1就是12
