### ISSUE TITLE
predict_api的正确使用

### ISSUE THREAD

**Issue by Zhenya97** [zepen/predict_Lottery_ticket#8]
大佬，就我训练结束后运行predict_api文件后一直卡在下图这里。我之前没有使用过微服务，希望大佬给点指导，感谢。

![1](https://user-images.githubusercontent.com/48851898/88618019-9e897080-d0ca-11ea-80d4-6e1fd07723fb.png)

**Comment by zepen** [comment]
1. 打开浏览器
2.在浏览器里输入：http://0.0.0.0:5000/predict_api
3.浏览应该会显示结果
