### ISSUE TITLE
接口输出号码，和计算结果集里的不一样

### ISSUE THREAD

**Issue by cctv888** [zepen/predict_Lottery_ticket#9]
predict_api.py
接口输出号码，和计算结果集里的不一样，被+1，这是个大坑，咳损失好几百万啊
return json.dumps({b_name: int(res) + 1

**Comment by cctv888** [comment]
训练的时候数据是从后往前推算，给数据的时候又从前往后给，怎么能算的对，坑货啊，又损失几百万

**Comment by cctv888** [comment]
6个号码左右相关性没有，有时还出现重复号码问题

**Comment by zepen** [comment]
> predict_api.py
> 接口输出号码，和计算结果集里的不一样，被+1，这是个大坑，咳损失好几百万啊
> return json.dumps({b_name: int(res) + 1

模型预测分类从 0开始的，号码应该是从1开始的，所以要➕1

**Comment by zepen** [comment]
> predict_api.py
> 接口输出号码，和计算结果集里的不一样，被+1，这是个大坑，咳损失好几百万啊
> return json.dumps({b_name: int(res) + 1

模型预测分类从 0开始的，号码应该是从1开始的，所以要➕1

> 6个号码左右相关性没有，有时还出现重复号码问题

**Comment by zepen** [comment]
> 6个号码左右相关性没有，有时还出现重复号码问题

当前建模，假设每个球出现号码是相互独立的，没有考虑出现球号码的序列，你感兴趣可自行改进建模方式。
